CREATE TABLE TB_PESSOA (
    idPessoa BIGINT IDENTITY(1,1) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    dataNascimento DATE NOT NULL
);

CREATE TABLE TB_CONTA (
    idConta BIGINT IDENTITY(1,1) PRIMARY KEY,
    idPessoa BIGINT NOT NULL,
    saldo DECIMAL(15,2) NOT NULL,
    limiteSaqueDiario DECIMAL(15,2),
    flagAtivo CHAR(1) NOT NULL,
    tipoConta INT NOT NULL,
    dataCriacao DATE NOT NULL,
    CONSTRAINT FK_CONTA_PESSOA FOREIGN KEY (idPessoa) REFERENCES TB_PESSOA(idPessoa)
);

CREATE TABLE TB_TRANSACAO (
    idTransacao BIGINT IDENTITY(1,1) PRIMARY KEY,
    idConta BIGINT NOT NULL,
    valor DECIMAL(15,2) NOT NULL,
    dataTransacao DATE NOT NULL,
    CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (idConta) REFERENCES TB_CONTA(idConta)
);
